import { LightningElement } from 'lwc';

export default class Employees extends LightningElement {
  employees = [
    {
      id: 1,
      checkboxId: 'employee-1',
      name: 'Michael Niall',
      employeeNumber: '12453234',
      status: 'Active',
      email: 'michael.niall@company.com',
      alternateEmail: 'mikeniall@gmail.com',
      link: '#',
      emailLink: 'mailto:michael.niall@company.com',
      alternateEmailLink: 'mailto:mikeniall@gmail.com'
    },
    {
      id: 2,
      checkboxId: 'employee-2',
      name: 'Melinda Miles',
      employeeNumber: '84763878',
      status: 'Active',
      email: 'melinda.miles@company.com',
      alternateEmail: 'mmiles@gmail.com',
      link: '#',
      emailLink: 'mailto:melinda.miles@company.com',
      alternateEmailLink: 'mailto:mmiles@gmail.com'
    },
    {
      id: 3,
      checkboxId: 'employee-3',
      name: 'Eric Stone',
      employeeNumber: '83729029',
      status: 'Active',
      email: 'eric.stone@company.com',
      alternateEmail: 'stoneeric@gmail.com',
      link: '#',
      emailLink: 'mailto:eric.stone@company.com',
      alternateEmailLink: 'mailto:stoneeric@gmail.com'
    },
    {
      id: 4,
      checkboxId: 'employee-4',
      name: 'Rohan Kharbanda',
      employeeNumber: '23456445',
      status: 'Active',
      email: 'rohan.kharbanda@company.com',
      alternateEmail: 'rohankhar@gmail.com',
      link: '#',
      emailLink: 'mailto:rohan.kharbanda@company.com',
      alternateEmailLink: 'mailto:rohankhar@gmail.com'
    },
    {
      id: 5,
      checkboxId: 'employee-5',
      name: 'Jake Hole',
      employeeNumber: '98765776',
      status: 'Active',
      email: 'jake.hole@company.com',
      alternateEmail: 'jacksonhole@gmail.com',
      link: '#',
      emailLink: 'mailto:jake.hole@company.com',
      alternateEmailLink: 'mailto:jacksonhole@gmail.com'
    },
    {
      id: 6,
      checkboxId: 'employee-6',
      name: 'Xavier Washington',
      employeeNumber: '17261562',
      status: 'Active',
      email: 'xavier.washington@company.com',
      alternateEmail: 'xavierwashington@outlook.com',
      link: '#',
      emailLink: 'mailto:xavier.washington@company.com',
      alternateEmailLink: 'mailto:xavierwashington@outlook.com'
    },
    {
      id: 7,
      checkboxId: 'employee-7',
      name: 'Reema Arcot Rey',
      employeeNumber: '49837224',
      status: 'Active',
      email: 'reema.a.rey@company.com',
      alternateEmail: 'reemaarcot@gmail.com',
      link: '#',
      emailLink: 'mailto:reema.a.rey@company.com',
      alternateEmailLink: 'mailto:reemaarcot@gmail.com'
    },
    {
      id: 8,
      checkboxId: 'employee-8',
      name: 'John Exeter',
      employeeNumber: '12345329',
      status: 'Active',
      email: 'john.exeter@company.com',
      alternateEmail: 'jexeter@gmail.com',
      link: '#',
      emailLink: 'mailto:john.exeter@company.com',
      alternateEmailLink: 'mailto:jexeter@gmail.com'
    },
    {
      id: 9,
      checkboxId: 'employee-9',
      name: 'Jessica Enes Valente',
      employeeNumber: '87645635',
      status: 'Active',
      email: 'jessica.e.valente@company.com',
      alternateEmail: 'jessicavalente12@gmail.com',
      link: '#',
      emailLink: 'mailto:jessica.e.valente@company.com',
      alternateEmailLink: 'mailto:jessicavalente12@gmail.com'
    },
    {
      id: 10,
      checkboxId: 'employee-10',
      name: 'Lydia Klauck',
      employeeNumber: '34567865',
      status: 'Active',
      email: 'lydia.klauck@company.com',
      alternateEmail: 'lydiaklauck@gmail.com',
      link: '#',
      emailLink: 'mailto:lydia.klauck@company.com',
      alternateEmailLink: 'mailto:lydiaklauck@gmail.com'
    },
    {
      id: 11,
      checkboxId: 'employee-11',
      name: 'Angel Britto',
      employeeNumber: '48973643',
      status: 'Active',
      email: 'angel.britto@company.com',
      alternateEmail: 'angelbritto35a@gmail.com',
      link: '#',
      emailLink: 'mailto:angel.britto@company.com',
      alternateEmailLink: 'mailto:angelbritto35a@gmail.com'
    },
    {
      id: 12,
      checkboxId: 'employee-12',
      name: 'Muigai Unaka',
      employeeNumber: '48736430',
      status: 'Active',
      email: 'muigai.unaka@company.com',
      alternateEmail: 'mui.unaka@gmail.com',
      link: '#',
      emailLink: 'mailto:muigai.unaka@company.com',
      alternateEmailLink: 'mailto:mui.unaka@gmail.com'
    },
    {
      id: 13,
      checkboxId: 'employee-13',
      name: 'Amira Al-meeda',
      employeeNumber: '87343890',
      status: 'Active',
      email: 'amira.almeeda@company.com',
      alternateEmail: 'amira.al@outlook.com',
      link: '#',
      emailLink: 'mailto:amira.almeeda@company.com',
      alternateEmailLink: 'mailto:amira.al@outlook.com'
    },
    {
      id: 14,
      checkboxId: 'employee-14',
      name: 'Angelica Flores',
      employeeNumber: '93847638',
      status: 'Active',
      email: 'angelica.flores@company.com',
      alternateEmail: 'angelica.flores@yahoo.com',
      link: '#',
      emailLink: 'mailto:angelica.flores@company.com',
      alternateEmailLink: 'mailto:angelica.flores@yahoo.com'
    },
    {
      id: 15,
      checkboxId: 'employee-15',
      name: 'Sherperd Yang',
      employeeNumber: '37463847',
      status: 'Active',
      email: 'sherperd.yang@company.com',
      alternateEmail: 'sherperdya@gmail.com',
      link: '#',
      emailLink: 'mailto:sherperd.yang@company.com',
      alternateEmailLink: 'mailto:sherperdya@gmail.com'
    },
    {
      id: 16,
      checkboxId: 'employee-16',
      name: 'Vineeth Nair',
      employeeNumber: '34876384',
      status: 'Active',
      email: 'vineeth.nair@company.com',
      alternateEmail: 'vineethnair@gmail.com',
      link: '#',
      emailLink: 'mailto:vineeth.nair@company.com',
      alternateEmailLink: 'mailto:vineethnair@gmail.com'
    },
    {
      id: 17,
      checkboxId: 'employee-17',
      name: 'Sarah Johnson',
      employeeNumber: '45678901',
      status: 'Active',
      email: 'sarah.johnson@company.com',
      alternateEmail: 'sarahj@gmail.com',
      link: '#',
      emailLink: 'mailto:sarah.johnson@company.com',
      alternateEmailLink: 'mailto:sarahj@gmail.com'
    },
    {
      id: 18,
      checkboxId: 'employee-18',
      name: 'David Chen',
      employeeNumber: '56789012',
      status: 'Active',
      email: 'david.chen@company.com',
      alternateEmail: 'davidchen@outlook.com',
      link: '#',
      emailLink: 'mailto:david.chen@company.com',
      alternateEmailLink: 'mailto:davidchen@outlook.com'
    },
    {
      id: 19,
      checkboxId: 'employee-19',
      name: 'Maria Garcia',
      employeeNumber: '67890123',
      status: 'Active',
      email: 'maria.garcia@company.com',
      alternateEmail: 'mariagarcia@yahoo.com',
      link: '#',
      emailLink: 'mailto:maria.garcia@company.com',
      alternateEmailLink: 'mailto:mariagarcia@yahoo.com'
    },
    {
      id: 20,
      checkboxId: 'employee-20',
      name: 'James Wilson',
      employeeNumber: '78901234',
      status: 'Active',
      email: 'james.wilson@company.com',
      alternateEmail: 'jwilson@gmail.com',
      link: '#',
      emailLink: 'mailto:james.wilson@company.com',
      alternateEmailLink: 'mailto:jwilson@gmail.com'
    }
  ];
}
